# Generated by Django 4.2.6 on 2023-10-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='provider_name',
        ),
    ]
