# Generated by Django 4.2.6 on 2023-10-22 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_remove_business_loan_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='month',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
            preserve_default=False,
        ),
    ]
