version: '3.9'


services:
  db:
    image: postgres:14-alpine
    ports:
      - '5432:5432'

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    volumes:
      - ./data/db:/var/lib/postgresql/data/

  client:
    build:
      context: ./client
      dockerfile: Dockerfile

    ports:
      - '3000:3000'

    volumes:
      - ./client/src:/app/client/src
      - ./client/index.html:/app/client/index.html
      - ./client/public:/app/client/public

    depends_on:
      - server

  server: 
    build: 
      context: ./server
      dockerfile: Dockerfile

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    ports:
      - '8000:8000'

    volumes:
      - ./server:/app/server

    depends_on:
      - db
